"""
scripts/load_oracle.py
Cria as tabelas no Oracle (se não existirem) e carrega os CSVs limpos.

Credenciais via variáveis de ambiente:
  ORACLE_USER, ORACLE_PASSWORD  (obrigatórias)
  ORACLE_DSN  (padrão: oracle.fiap.com.br:1521/ORCL)
"""

import logging
import os

import oracledb as cx_Oracle
import pandas as pd

logger = logging.getLogger(__name__)

# ─── DDL ──────────────────────────────────────────────────────────────────────

DDL_ISS = """
CREATE TABLE ISS_POSITIONS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIMESTAMP_UNIX  NUMBER(20)       NOT NULL,
    TIMESTAMP_UTC   TIMESTAMP        NOT NULL,
    LATITUDE        NUMBER(10, 6)    NOT NULL,
    LONGITUDE       NUMBER(10, 6)    NOT NULL,
    HORA_UTC        NUMBER(2),
    QUADRANTE       VARCHAR2(3),
    MESSAGE         VARCHAR2(50),
    INGESTION_TS    VARCHAR2(30),
    SOURCE          VARCHAR2(50),
    CONSTRAINT uq_iss_ts UNIQUE (TIMESTAMP_UNIX)
)
"""

DDL_NEO = """
CREATE TABLE NEO_OBJECTS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NEO_ID          VARCHAR2(20)     NOT NULL,
    NOME            VARCHAR2(200),
    DATA_REFERENCIA DATE             NOT NULL,
    DATA_APROXIMACAO VARCHAR2(50),
    DIAMETRO_KM_AVG NUMBER(12, 6),
    VELOCIDADE_KMS  NUMBER(12, 6),
    DISTANCIA_KM    NUMBER(20, 3),
    IS_PERIGOSO     NUMBER(1)        DEFAULT 0,
    MAGNITUDE       NUMBER(8, 3),
    INGESTION_TS    VARCHAR2(30),
    SOURCE          VARCHAR2(50),
    CONSTRAINT uq_neo UNIQUE (NEO_ID, DATA_REFERENCIA)
)
"""


def _get_connection() -> cx_Oracle.Connection:
    user     = os.environ["ORACLE_USER"]
    password = os.environ["ORACLE_PASSWORD"]
    host     = os.environ.get("ORACLE_HOST", "oracle.fiap.com.br")
    port     = int(os.environ.get("ORACLE_PORT", "1521"))
    sid      = os.environ.get("ORACLE_SID", "ORCL")
    return cx_Oracle.connect(user=user, password=password, host=host, port=port, sid=sid)


def _ensure_table(cursor: cx_Oracle.Cursor, ddl: str, table_name: str) -> None:
    """Cria a tabela se ainda não existir."""
    cursor.execute(
        "SELECT COUNT(*) FROM user_tables WHERE table_name = :t",
        {"t": table_name},
    )
    (count,) = cursor.fetchone()
    if count == 0:
        logger.info("Criando tabela %s...", table_name)
        cursor.execute(ddl)
        logger.info("Tabela %s criada.", table_name)
    else:
        logger.info("Tabela %s já existe, pulando criação.", table_name)


# ─── Carga ISS ────────────────────────────────────────────────────────────────

def _load_iss(cursor: cx_Oracle.Cursor, df: pd.DataFrame) -> int:
    sql = """
        INSERT INTO ISS_POSITIONS
            (TIMESTAMP_UNIX, TIMESTAMP_UTC, LATITUDE, LONGITUDE,
             HORA_UTC, QUADRANTE, MESSAGE, INGESTION_TS, SOURCE)
        VALUES
            (:1, TO_TIMESTAMP(:2, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
             :3, :4, :5, :6, :7, :8, :9)
    """
    rows = []
    for _, r in df.iterrows():
        ts_utc = str(r["TIMESTAMP_UTC"])[:19].replace(" ", "T") + "Z"
        rows.append((
            int(r["TIMESTAMP_UNIX"]),
            ts_utc,
            float(r["LATITUDE"]),
            float(r["LONGITUDE"]),
            int(r["HORA_UTC"]),
            str(r["QUADRANTE"]),
            str(r.get("MESSAGE", "")),
            str(r.get("INGESTION_TS", "")),
            str(r.get("SOURCE", "")),
        ))

    inserted = 0
    for row in rows:
        try:
            cursor.execute(sql, row)
            inserted += 1
        except cx_Oracle.IntegrityError:
            pass  # duplicata, ignora

    return inserted


# ─── Carga NEO ────────────────────────────────────────────────────────────────

def _load_neo(cursor: cx_Oracle.Cursor, df: pd.DataFrame) -> int:
    sql = """
        INSERT INTO NEO_OBJECTS
            (NEO_ID, NOME, DATA_REFERENCIA, DATA_APROXIMACAO,
             DIAMETRO_KM_AVG, VELOCIDADE_KMS, DISTANCIA_KM,
             IS_PERIGOSO, MAGNITUDE, INGESTION_TS, SOURCE)
        VALUES
            (:1, :2, TO_DATE(:3, 'YYYY-MM-DD'), :4,
             :5, :6, :7, :8, :9, :10, :11)
    """
    inserted = 0
    for _, r in df.iterrows():
        try:
            cursor.execute(sql, (
                str(r["NEO_ID"]),
                str(r["NOME"]),
                str(r["DATA_REFERENCIA"])[:10],
                str(r.get("DATA_APROXIMACAO", "")),
                float(r["DIAMETRO_KM_AVG"]) if pd.notna(r["DIAMETRO_KM_AVG"]) else None,
                float(r["VELOCIDADE_KMS"])   if pd.notna(r["VELOCIDADE_KMS"])   else None,
                float(r["DISTANCIA_KM"])     if pd.notna(r["DISTANCIA_KM"])     else None,
                1 if r["IS_PERIGOSO"] else 0,
                float(r["MAGNITUDE"])        if pd.notna(r["MAGNITUDE"])        else None,
                str(r.get("INGESTION_TS", "")),
                str(r.get("SOURCE", "")),
            ))
            inserted += 1
        except cx_Oracle.IntegrityError:
            pass  # duplicata, ignora

    return inserted


# ─── Task principal ───────────────────────────────────────────────────────────

def load_oracle(data_dir: str, **context) -> None:
    iss_path = os.path.join(data_dir, "iss_clean.csv")
    neo_path = os.path.join(data_dir, "neo_clean.csv")

    df_iss = pd.read_csv(iss_path)
    df_neo = pd.read_csv(neo_path)

    logger.info("Conectando ao Oracle...")
    conn   = _get_connection()
    cursor = conn.cursor()

    try:
        _ensure_table(cursor, DDL_ISS, "ISS_POSITIONS")
        _ensure_table(cursor, DDL_NEO, "NEO_OBJECTS")

        n_iss = _load_iss(cursor, df_iss)
        n_neo = _load_neo(cursor, df_neo)

        conn.commit()
        logger.info("Carga concluída | ISS: %d registros | NEO: %d registros",
                    n_iss, n_neo)
    except Exception as e:
        conn.rollback()
        logger.error("Erro na carga, rollback executado: %s", e)
        raise
    finally:
        cursor.close()
        conn.close()
